# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

arePosInts <- function(xs) {
    .Call('_chR_arePosInts', PACKAGE = 'chR', xs)
}

areNegInts <- function(xs) {
    .Call('_chR_areNegInts', PACKAGE = 'chR', xs)
}

areNatInts <- function(xs) {
    .Call('_chR_areNatInts', PACKAGE = 'chR', xs)
}

