# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Returns true iff all the xs are positive
#' @param xs
#' @export
arePosInts <- function(xs) {
    .Call('_chR_arePosInts', PACKAGE = 'chR', xs)
}

#' Returns true iff all the xs are negative
#' @param xs
#' @export
areNegInts <- function(xs) {
    .Call('_chR_areNegInts', PACKAGE = 'chR', xs)
}

#' Returns true iff all the xs are naturals (>= 0)
#' @param xs
#' @export
areNatInts <- function(xs) {
    .Call('_chR_areNatInts', PACKAGE = 'chR', xs)
}

